= About
:page-layout: single
:page-permalink: /about/

Welcome to jwillikers.com, where I like to put all of my handy admin and dev guides from my myriad of tinkering.
My posts serve not only as convenient references for my future self, but also force me to learn and understand the different technologies I end up touching.
Hopefully, the content here will help other tinkerers, technologists, and developers.

== Me

Here I take the opportunity to talk a bit about myself, my development experience, and interests.

=== Career

The reasons I pursue a career in software engineering have continued to grow and evolve over time.
Suffice it to say that I enjoy participating as part of a team to solve real and interesting problems.
I find it important and fulfilling that these solutions positively impact the lives of others.

As a software engineer, I strive to write the least amount of simple and safe code required to complete a given task.
Ideally, this amounts to writing no code at all because I'm able to discover that a perfectly adequate and tenable solution already exists.

In the sections which follow I describe my experience in the field.

==== Cross-platform Application Development

At my current day job, I wrangle https://isocpp.org/[{cpp}] and https://cmake.org/[CMake] code to create functional, cross-platform graphical applications.
Developing at a small company, my hands are in just about everything from project management and cross-platform application development to systems administration and licensing compliance.
My focus here has been to learn how to write good {cpp} code, to improve the build system, and to implement both standard software engineering practices and agile development models.

It has been challenging to implement better practices and processes while both maintaining a large, legacy code-bas elacking any standards what-so-ever and adding high-quality code for new features.
This is has been a phenomenal learning opportunity, in a trial-by-fire way.
Such circumstances have bred in me a deep appreciation of the software engineering principles and development practices which foster the production of maintainable code.
This endeavor has also lead me to understand how the process of writing good code is impacted by management, project planning, collaboration, communication, and even company culture.

==== Software Engineering Intern

Previously, I interned at a cyber security company which developed log-analyzing security software.
This was my first real introduction to software engineering, where I had the privilege to be a part of the backend developer team.
This is where I learned first-hand how the fundamental software engineering practices such as version control, testing, code-reviews, continuous integration, and deployment all fit together.
My work their included Java, Python, and Awk development as well as work on the Gradle build-system and integrating deployment to Docker.
I even underwent certification as a https://www.scrum.org/[Scrum] master.

==== Data Analyst

Before that, I interned as a data analyst at a healthcare institution.
This lead to lots of SQL development and digging through backend databases.
I became proficient at writing complex SQL queries, but most importantly, I was forced to think critically.
I constantly had to question, "Where is this data coming from?" and, "What does this _really_ mean?" at all times.

=== Education

I graduated with a bachelor's degree in Computer Science with a concentration in Information Insurance.
Although I prefer the applied, a degree in the more theoretical aspects of Computer Science was quite rewarding, stretching me to understand the underpinning aspects of computing.
The experience in cyber security brought with it a cautious and proactive mindset, which influences how I think about and write code today.

=== Development Preferences

I like writing code to make people's lives easier.
Unfortunately, I've learned from experience that poor code has a tendency to make the lives of everyone more difficult, especially for developers.
This has ingrained in me strong convictions for utilizing standard software engineering practices, high-quality open source software, and the best tooling available to create safe and maintainable code.

There is also nothing like having fun and learning new things while solving a challenging problem.
This is why languages which pursue safety and simplicity, such as Rust and Go, are my favorites.
They tend allow me to focus on the problem at hand rather than frustrate me with issues and complexities inherent in the language.

=== Interests

If you haven't figured it out yet, I'm big proponent of open-source software where high-quality solutions to common problems abound.
I enjoy collaborating with other developers to improve open-source software for everyone.

* Desktop Linux, namely https://ubuntu.com/download/desktop[Ubuntu] and https://www.gnome.org/[GNOME]
* Open-hardware mobile devices (and relevant software), such as the https://pine64.org/devices/pinebook_pro/[Pinebook Pro], https://www.pine64.org/pinephone/[PinePhone], and https://pine64.org/devices/pinetab/[PineTab] developed by https://www.pine64.org/[Pine64]
* Safe, simple, and easy-to-use programming languages like https://www.rust-lang.org/[Rust] and https://golang.org/[Go]
* https://www.openbsd.org/[OpenBSD]
* https://www.freebsd.org/[FreeBSD]
* https://openzfs.org/wiki/Main_Page[OpenZFS]
* https://riscv.org/[RISC-V]

=== Hobbies

As for hobbies outside of tech, I enjoy spending time with my wife, yoga, cooking, socializing, listening to podcasts and books, hiking, and generally getting outside whenever possible.

=== Technologies

Below I enumerate the technologies with which I am familiar.

Operating Systems::
* https://ubuntu.com/[Ubuntu]
* https://www.openbsd.org/[OpenBSD]
* https://elementary.io/[elementaryOS]
* https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux[Red Hat Enterprise Linux]
* https://www.debian.org/[Debian]
* https://getfedora.org/[Fedora]
* https://www.gentoo.org/[Gentoo]
* https://manjaro.org/[Manjaro]
* https://mobian-project.org/[Mobian]
* https://www.opensuse.org/[openSUSE]
* https://openwrt.org/[OpenWrt]
* macOS
* Windows

Languages::
* https://asciidoctor.org/[Asciidoctor]
* https://www.gnu.org/software/gawk/manual/gawk.html[awk]
* https://tiswww.case.edu/php/chet/bash/bashtop.html[Bash]
* http://www.open-std.org/jtc1/sc22/wg14/[C]
* https://isocpp.org/[{cpp}] (Standards including 98, 11, 14, 17, 20)
* https://fishshell.com/[fish]
* https://golang.org/[Go]
* https://golang.org/[Java]
* https://www.python.org/[Python]
* https://www.microsoft.com/en-us/sql-server[SQL Server]
* https://toml.io/en/[TOML]
* https://www.zsh.org/[ZSH]

Frameworks::
* https://www.djangoproject.com/[Django]
* https://www.gtkmm.org/en/[Gtkmm]
* https://www.qt.io/[Qt5]
* https://jekyllrb.com/[Jekyll]
* https://gohugo.io/[Hugo]

Compilers::
* https://gcc.gnu.org/[GCC]
* https://clang.llvm.org/[LLVM Clang]
* https://visualstudio.microsoft.com/vs/features/cplusplus/[MSVC]

Build Tooling::
* https://asdf-vm.com/#/[asdf]
* [Bundler]
* https://ccache.dev/[ccache]
* https://cmake.org/[CMake]
* https://conan.io/[Conan]
* https://ninja-build.org/[Ninja]
* https://pipenv.pypa.io/en/latest/[Pipenv]
* https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=msvc-160[vcpkg]

Packaging::
* https://appimage.org/[AppImage]
* https://manpages.debian.org/unstable/dpkg-dev/deb.5.en.html[deb]
* https://github.com/linuxdeploy/linuxdeploy[linuxdeploy]
* https://en.wikipedia.org/wiki/Bundle_(macOS)[macOS Bundle]
* https://nsis.sourceforge.io/Main_Page[NSIS]
* https://rpm.org/[RPM]

Code Quality / Correctness::
* https://approvaltestscpp.readthedocs.io/en/latest/[Approval Tests.cpp]
* https://www.boost.org/doc/libs/1_74_0/libs/test/doc/html/index.html[Boost.Test]
* https://boost-ext.github.io/ut/[[Boost::ext\].μt]
* https://github.com/catchorg/Catch2[Catch2]
* https://clang.llvm.org/extra/clang-tidy/[Clang-Tidy]
* http://clang.llvm.org/docs/ClangFormat.html[ClangFormat]
* https://github.com/google/benchmark[Google Benchmark]
* https://github.com/google/sanitizers[Google Sanitizers]
* https://github.com/google/googletest[Google Test]
* https://valgrind.org/[Valgrind]

Libraries::
* https://www.boost.org/doc/libs/1_74_0/doc/html/boost_asio.html[Boost.Asio]
* https://www.boost.org/doc/libs/1_74_0/libs/concept_check/concept_check.htm[The Boost Concept Check Library]
* https://www.boost.org/doc/libs/1_74_0/libs/contract/doc/html/index.html[Boost.Contract]
* https://www.boost.org/doc/libs/1_74_0/libs/filesystem/doc/index.htm[Boost Filesystem]
* https://www.boost.org/doc/libs/1_74_0/doc/html/interprocess.html[Boost.Interprocess]
* https://www.boost.org/doc/libs/1_74_0/doc/html/process.html[Boost.Process]
* https://www.boost.org/doc/libs/1_74_0/libs/spirit/doc/x3/html/index.html[Boost Spirit X3]
* https://fmt.dev/latest/index.html[fmt]
* https://github.com/microsoft/GSL[Microsoft GSL]
* https://www.openmp.org/[OpenMP]
* https://www.open-mpi.org/[OpenMPI]
* https://marzer.github.io/tomlplusplus/[tomlplusplus]

Editors and IDEs::
* https://atom.io/[Atom]
* https://godbolt.org/[Compiler Explorer]
* https://www.eclipse.org/downloads/[Eclipse]
* https://www.jetbrains.com/clion/[JetBrains CLion]
* https://www.jetbrains.com/idea/[JetBrains Intellij]
* https://www.sublimemerge.com/[Sublime Merge]
* https://www.sublimetext.com/[Sublime Text]
* https://www.vim.org/[Vim]
* https://code.visualstudio.com/[Visual Studio Code]
* https://vscodium.com/[VSCodium]

Continuous Integration::
* https://www.jenkins.io/[Jenkins]
* https://travis-ci.org/[Travis CI]

Virtualization::
* https://www.docker.com/[Docker]
* https://wiki.gnome.org/Apps/Boxes[GNOME Boxes]
* https://libvirt.org/[libvirt]
* https://multipass.run/[Multipass]
* https://www.qemu.org/[QEMU]
* https://www.vagrantup.com/[Vagrant]
* https://virt-manager.org/[Virtual Machine Manager]
* https://www.virtualbox.org/[VirtualBox]
* https://www.virtualbox.org/[VMWare Fusion]

Networking::
* https://www.openssh.com/[OpenSSH]
* https://www.openbsd.org/faq/pf/index.html[PF]
* https://www.unbound.org/[Unbound]
* https://www.wireguard.com/[WireGuard]

System Utilities::
* https://en.wikipedia.org/wiki/Cron[cron]
* https://opensource.apple.com/tarballs/launchd/[launchd]
* https://en.wikipedia.org/wiki/Pluggable_authentication_module[PAM]
* https://systemd.io/[Systemd]
* https://www.sudo.ws/[Sudo]

Filesystems::
* https://openzfs.org/wiki/Main_Page[OpenZFS]

Services::
* https://nextcloud.com/[Nextcloud]
* https://syncthing.net/[Syncthing]

Version Control::
* https://git-scm.com/[Git]

Currently Learning::
* https://www.rust-lang.org/[Rust]
