[default]
extend-ignore-re = [
  "sha256[[:space:]]*=[[:space:]]*\"[[:alnum:]]+\"",
  "SHA256:[[:space:]]*[[a-zA-Z0-9+]]+[[:space:]]*",
]

[default.extend-identifiers]
96AFE6CB = "96AFE6CB"

[default.extend-words]
hda = "hda"
