baseURL = "http://jwillikers.com/"
languageCode = "en-us"
title = "JWillikers"
theme = "beautifulhugo"
enableEmoji = true
enableGitInfo = true
pygmentsStyle = "solarized-light"
pygmentsCodeFences = true
pygmentsUseClasses = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-light"
    tabWidth = 4

[Params]
  subtitle = "My developer website"
  rss = true
  mainSections = ["post","posts"]
  logo = "https://www.gravatar.com/avatar/e3189498d000ca4eb4e893739fd63636?s=500"

[Author]
	name = "Jordan Williams"
    github = "jwillikers"
    gitlab = "jwillikers"
    bitbucket = "jwillikers"
    custom_css = ["css/custom.css"]

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/jwillikers/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/jwillikers/"
[[params.social]]
    name = "Bitbucket"
    icon = "fab fa-bitbucket fa-2x"
    weight = 2
    url = "https://bitbucket.org/jwillikers/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
