baseURL = "http://jwillikers.com/"
languageCode = "en-us"
title = "JWillikers"
theme = "coder"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-light"
    tabWidth = 4

[params]
	author = "Jordan Williams"
	info = "Software Developer"
	description = "My developer website"
	keywords = "blog,developer"
	avatarurl = "https://www.gravatar.com/avatar/e3189498d000ca4eb4e893739fd63636?s=500"

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/jwillikers/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/jwillikers/"
[[params.social]]
    name = "Bitbucket"
    icon = "fab fa-bitbucket fa-2x"
    weight = 2
    url = "https://bitbucket.org/jwillikers/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
