baseURL = "https://jwillikers.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "JWillikers"
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true

#gravatarEmail = "jordan@jwillikers.com"
#avatarURL = "https://www.gravatar.com/avatar/e3189498d000ca4eb4e893739fd63636?s=500"

#pygmentsOptions = "linenos=table"
#pygmentsCodefences = true
#pygmentsUseClasses = true
#pygmentsCodefencesGuessSyntax = false

paginate = 5
copyright = '''
Jordan Williams
<br />
<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
<img alt="Creative Commons License" style="border-width:0"
  src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a>
<br />
<span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/Text"
  property="dct:title" rel="dct:type">JWillikers</span> by 
  <a xmlns:cc="http://creativecommons.org/ns#" href="https://jwillikers.com"
  property="cc:attributionName" rel="cc:attributionURL">Jordan Williams</a>
  is licensed under a 
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
  Creative Commons Attribution-ShareAlike 4.0 International License</a>.
'''

[module]
  [[module.imports]]
    path = "github.com/olOwOlo/hugo-theme-even"

[author]
  name = "Jordan Williams"
  email = "jordan@jwillikers.com"

[[menu.main]]
  name = "Archives"
  weight = 10
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 20
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Categories"
  weight = 30
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "Resources"
  weight = 40
  identifier = "resources"
  url = "/resources/"
[[menu.main]]
  name = "About"
  weight = 50
  identifier = "about"
  url = "/about/"


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4
    style = "solarized-light"
    hl_Lines = ""
    lineNoStart = 1
  [markup.asciidocext]
    backend = "html5s"
    extensions = ["asciidoctor-html5s"]
    workingFolderCurrent = true
    trace = true
    [markup.asciidocext.attributes]
    experimental = ""
    source-highlighter = "rouge"
    rouge-style = "base16.solarized.light"
    icons = "font"
    relfileprefix = "../"
    outfilesuffix = "/"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  version = "4.x" # Used to give a friendly message when you have an incompatible update
  debug = false # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  archivePaginate = 50 
  since = "2020" # Site creation time
  gitRepo = "https://github.com/jwillikers/blog" 

  logoTitle = "JWillikers" # default: the title value
  keywords = ["Blog", "BSD", "Linux"] 
  description = "Handy admin and dev guides from my myriad of tinkering" 

  showArchiveCount = false

  dateFormatToUse = "2006-01-02"

  moreMeta = false

  highlightInClient = true

  toc = true
  autoCollapseToc = false # Auto expand and collapse toc

  # see https://github.com/fancyapps/fancybox
  fancybox = true

  # mathjax see https://www.mathjax.org/
  mathjax = false
  mathjaxEnableSingleDollar = false
  mathjaxEnableAutoNumber = false
  mathjaxUseLocalFiles = false # You should install mathjax in `your-site/static/lib/mathjax`

  # contain author, lastMod, markdown link, license
  postMetaInFooter = false
  contentCopyright = '''
&copy; 2020 Jordan Williams
<br />
<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
<img alt="Creative Commons License" style="border-width:0"
  src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a>
<br />
<span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/Text"
  property="dct:title" rel="dct:type">JWillikers</span> by 
  <a xmlns:cc="http://creativecommons.org/ns#" href="https://jwillikers.com"
  property="cc:attributionName" rel="cc:attributionURL">Jordan Williams</a>
  is licensed under a 
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
  Creative Commons Attribution-ShareAlike 4.0 International License</a>.
'''

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = [ "syntax.css" ]
  customJS = []

  uglyURLs = false # please keep same with uglyurls setting

[params.social]
  a-github = "https://github.com/jwillikers"
  b-gitlab = "https://gitlab.com/jwillikers"
  c-stack-overflow = "https://stackoverflow.com/users/9835303/"
  d-email = "mailto:jordan@jwillikers.com"

[outputs]
  home = ["HTML", "RSS", "JSON"]
