baseURL = "https://jwillikers.com/"
languageCode = "en-us"
title = "JWillikers"
theme = "beautifulhugo"
enableEmoji = true
enableGitInfo = true
pygmentsStyle = "default"
pygmentsCodeFences = true
pygmentsUseClasses = true

[markup]
  [markup.asciidocext]
    backend = "html5s"
    extensions = ["asciidoctor-html5s"]
    workingFolderCurrent = true
    trace = true
    [markup.asciidocext.attributes]
        source-highlighter = "rouge"
        rouge-style = "github"
        icons = "font"
        relfileprefix = "../"
        outfilesuffix = "/"

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-dark"
    tabWidth = 4

[Params]
    subtitle = "Handy admin and dev guides from my myriad of tinkering"
    rss = true
    mainSections = ["post","posts"]
    logo = "https://www.gravatar.com/avatar/e3189498d000ca4eb4e893739fd63636?s=500"

[Author]
	name = "Jordan Williams"
    github = "jwillikers"
    gitlab = "jwillikers"
    bitbucket = "jwillikers"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Resources"
    weight = 3
    url = "/resources/"
[[menu.main]]
    name = "Contact"
    weight = 4
    url = "/contact/"
