# Due to rate limiting from https://www.gnu.org
accept = [429]

cache = true
exclude = [
  '^http://www\.gnu\.org',
  # 403 forbidden when running in GitHub Actions
  '^https://arstechnica\.com',
  '^https://127\.0\.0\.1:8443/',
  '^https://flatpak\.org',
  '^https://ftp\.gnu\.org',
  '^https://linuxize.com/post/how-to-add-user-to-sudoers-in-ubuntu/',
  '^https://opensource\.org/license/gpl-2-0',
  '^https://rouge.jneen.net/',
  # Error, for some reason?
  '^https://wayland\.freedesktop\.org',
  '^https://wilsonmar\.github\.io',
  '^https://www\.centos\.org',
  '^https://www\.denx\.de/wiki/U-Boot',
  '^https://www\.geoghegan\.ca',
  '^https://www\.gnome\.org',
  '^https://www\.gnu\.org',
  # 403 forbidden when running in GitHub Actions
  '^https://www\.scrum\.org',
]
# exclude_path = ["_site/", "result/"]
max_cache_age = "2w"
