# Due to rate limiting from https://www.gnu.org
accept = [429]

cache = true
exclude = [
  '^https://127\.0\.0\.1:8443/',
  '^https://linuxize.com/post/how-to-add-user-to-sudoers-in-ubuntu/',
  '^https://opensource\.org/license/gpl-2-0',
  '^https://rouge.jneen.net/',
]
# exclude_path = ["_site/", "result/"]
max_cache_age = "2w"
