= Blog
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

My developer blog containing handy admin and dev guides from my myriad of tinkering.
Content is written primarily in https://asciidoctor.org/[Asciidoctor].
https://jekyllrb.com/[Jekyll] generates a static website from the content which is then deployed with https://pages.github.com/[GitHub Pages].
The website is available at https://jwillikers.com[jwillikers.com].

== Contributing

Contributions in the form of issues, feedback, and even pull requests are welcome.
I really appreciate pointing out typos, incorrect instructions, and ways to improve or simplify posts.
Considering this my personal blog, you will want to create an issue or contact me before making any significant pull request.
Make sure to adhere to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].
If you wish to test the website locally, please see <<Getting Started>>.

== Getting Started

The steps below will create an environment for generating the website locally.
These steps assume you are on Fedora and familiar with the Linux command-line and https://git-scm.com/[Git].

. Clone the blog's repository.
+
[,sh]
----
git -C ~/Projects clone git@github.com:jwillikers/blog.git
----

. Change into the blog's directory.
+
[,sh]
----
cd ~/Projects/blog
----

. Install the dependencies needed for asdf.
+
[,sh]
----
sudo dnf -y install gcc gcc-c++ libffi-devel ruby-devel rubygem-bundler
----

. Configure a project-specific directory for Gems.
+
[,sh]
----
bundle config set --local path 'vendor/bundle'
----

. Install the required Ruby gems.
+
[,sh]
----
bundle install
----

== Build

The website can be generated locally by passing the `b` subcommand, i.e. _build_, to Jekyll.

[,sh]
----
bundle exec jekyll b
----

== Test

Jekyll supports running a web server on the local machine, which can be used to preview and test changes to the website.
The steps below describe how to do this below, assuming you are in the project directory running Ubuntu with the GNOME desktop.

. Run the `jekyll` executable with the `s` subcommand, i.e. _serve_.
+
[,sh]
----
bundle exec jekyll s
Configuration file: /home/jordan/Source/blog/_config.yml
            Source: /home/jordan/Source/blog
       Destination: /home/jordan/Source/blog/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
 Auto-regeneration: enabled for '/home/jordan/Source/blog'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
----

. Open the server address provided in the previous output with your web browser of choice.
+
[,sh]
----
open http://127.0.0.1:4000/
----

. When finished testing, type kbd:[Ctrl+C] to stop the local web server.

== Deploy

Continuous integration is configured through GitHub Actions.
Trigger the CI to build and deploy by pushing changes to the `main` branch on the GitHub remote.

[,sh]
----
git push
----

The updated website is deployed to https://jwillikers.com[jwillikers.com].

== Update

Update the Gems with the `bundle update` command.

[,sh]
----
bundle update
----

== Open Source Software

This project is built on the hard work of countless open source contributors.
Several of these projects are enumerated below.

* https://asciidoctor.org/[asciidoctor]
* https://bundler.io/[Bundler]
* https://git-scm.com/[Git]
* https://jekyllrb.com/[Jekyll]
* https://github.com/asciidoctor/jekyll-asciidoc[jekyll-asciidoc]
* https://mmistakes.github.io/minimal-mistakes/[Minimal Mistakes]
* https://rouge.jneen.net/[Rouge]
* https://www.ruby-lang.org/en/[Ruby]

== Code of Conduct

The project's Code of Conduct is available in the link:CODE_OF_CONDUCT.adoc[] file.

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3], available in the link:LICENSE.adoc[] file.

The website's content is licensed under a http://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution-ShareAlike 4.0 International License].

© 2020-2024 Jordan Williams

== Authors

mailto:{email}[{author}]
