= Blog
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

My developer blog containing handy admin and dev guides from my myriad of tinkering.
Content is written primarily in https://asciidoctor.org/[Asciidoctor].
https://jekyllrb.com/[Jekyll] generates a static website from the content which is then deployed with https://pages.github.com/[GitHub Pages].
The website is available at https://jwillikers.com[jwillikers.com].

== Contributing

Contributions in the form of issues, feedback, and even pull requests are welcome.
I really appreciate pointing out typos, incorrect instructions, and ways to improve or simplify posts.
Considering this my personal blog, you will want to create an issue or contact me before making any significant pull request.
Make sure to adhere to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].
If you wish to test the website locally, please see <<Getting Started>>.

== Getting Started

The steps below will create an environment for generating the website locally.
These steps assume you are on https://ubuntu.com/[Ubuntu] and familiar with the Linux command-line and https://git-scm.com/[Git].
Instructions are provided for the https://www.gnu.org/software/bash/[Bash], https://fishshell.com/[fish], and https://www.zsh.org/[ZSH] shells.

. Clone the blog's repository.
+
[source,sh]
----
➜ git clone git@github.com:jwillikers/blog.git
----

. Change into the blog's directory.
+
[source,sh]
----
➜ cd blog
----

. Install the dependencies needed for asdf.
+
[source,sh]
----
➜ sudo apt -y install curl git
----

. Pull down the https://github.com/asdf-vm/asdf[asdf repository] in to your home directory.
+
[source,sh]
----
➜ git clone https://github.com/asdf-vm/asdf.git ~/.asdf
Cloning into '/home/ubuntu/.asdf'...
remote: Enumerating objects: 145, done.
remote: Counting objects: 100% (145/145), done.
remote: Compressing objects: 100% (85/85), done.
remote: Total 5782 (delta 76), reused 93 (delta 59), pack-reused 5637
Receiving objects: 100% (5782/5782), 1.09 MiB | 6.01 MiB/s, done.
Resolving deltas: 100% (3293/3293), done.
----

. Checkout the latest version of asdf.
+
--
_fish_::
+
[source,sh]
----
➜ git -C ~/.asdf switch --detach (git -C ~/.asdf describe --abbrev=0 --tags)
HEAD is now at c6145d0 Update version to 0.8.0
----

_Bash / ZSH_::
+
[source,bash]
----
➜ git -C ~/.asdf switch --detach $(git -C ~/.asdf describe --abbrev=0 --tags)
HEAD is now at c6145d0 Update version to 0.8.0
----
--

. Enable asdf in your shell.
+
--
_fish_::
+
[source,sh]
----
➜ mkdir -p ~/.config/fish/conf.d; and echo "source ~/.asdf/asdf.fish" > ~/.config/fish/conf.d/asdf.fish
----

_Bash_::
+
[source,bash]
----
➜ echo '. $HOME/.asdf/asdf.sh' >> ~/.bashrc
----

_ZSH_::
+
[source,zsh]
----
➜ echo '. $HOME/.asdf/asdf.sh' >> ~/.zshrc
----
--

. Install shell completions for asdf.
+
--
_fish_::
+
[source,sh]
----
➜ mkdir -p ~/.config/fish/completions; and ln -s ~/.asdf/completions/asdf.fish ~/.config/fish/completions
----

_Bash_::
+
[source,bash]
----
➜ echo '. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc
----

_ZSH_::
+
[source,zsh]
----
➜ echo -e 'fpath=(${ASDF_DIR}/completions $fpath)\nautoload -Uz compinit\ncompinit' >> ~/.zshrc
----
--

. Reload fish to make asdf available.
+
--
_fish_::
+
[source,sh]
----
➜ exec fish
----

_Bash_::
+
[source,bash]
----
➜ source ~/.bashrc
----

_ZSH_::
+
[source,zsh]
----
➜ source ~/.zshrc
----
--

. Install the requisite packages for building Ruby.
+
[source,sh]
----
➜ sudo apt -y install autoconf bison build-essential libssl-dev libyaml-dev \
  libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev \
  libdb-dev
----

. Add asdf plugins for direnv, Bundler, and Ruby.
+
[source,sh]
----
➜ asdf plugin add bundler direnv ruby
----

. Integrate direnv with your shell.
+
--
_fish_::
+
[source,sh]
----
➜ mkdir -p ~/.config/fish/conf.d; \
  and echo "asdf exec direnv hook fish | source" > ~/.config/fish/conf.d/direnv.fish
----

_Bash_::
+
[source,bash]
----
➜ echo 'eval "$(asdf exec direnv hook bash)"' >> ~/.bashrc
----

_ZSH_::
+
[source,zsh]
----
➜ echo 'eval "$(asdf exec direnv hook zsh)"' >> ~/.zshrc
----
--

. Make the asdf feature, i.e. the command `use asdf`, available in direnv.
+
--
_fish_::
+
[source,sh]
----
➜ mkdir -p ~/.config/direnv; \ 
  and echo 'source "$(asdf direnv hook asdf)"' >> ~/.config/direnv/direnvrc
----

_Bash / ZSH_::
+
[source,bash]
----
➜ mkdir -p ~/.config/direnv; \
  echo 'source "$(asdf direnv hook asdf)"' >> ~/.config/direnv/direnvrc
----

NOTE: The `direnvrc` file should only use Bash syntax.
--

. Install the project's asdf dependencies.
+
[source,sh]
----
➜ asdf install
----

. Allow direnv to alter the environment for the project directory.
+
[source,sh]
----
➜ direnv allow
----

. Install the required Ruby gems.
+
[source,sh]
----
➜ bundle
----

== Test

Jekyll supports running a web server on the local machine, which can be used to preview and test changes to the website.
The steps below describe how to do this below, assuming you are in the project directory running Ubuntu with the GNOME desktop.

. Run the `jekyll` executable with the `s` subcommand, i.e. _serve_.
+
[source,sh]
----
➜ jekyll s
Configuration file: /home/jordan/Source/blog/_config.yml
            Source: /home/jordan/Source/blog
       Destination: /home/jordan/Source/blog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
 Auto-regeneration: enabled for '/home/jordan/Source/blog'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
----

. Open the server address provided in the previous output with your web browser of choice.
+
[source,sh]
----
➜ gnome-www-browser http://127.0.0.1:4000/
----

. When finished testing, type kbd:[Ctrl+C] to stop the local web server.

== Build

The website can be generated locally by passing the `b` subcommand, i.e. _build_, to Jekyll.

[source,sh]
----
➜ jekyll b
----

== Deploy

Continuous integration is configured through https://travis-ci.org/[Travis CI].
Trigger the CI to build and deploy by pushing changes to the `master` branch on the GitHub remote.

[source,sh]
----
➜ git push
----

The updated website is deployed to https://jwillikers.com[jwillikers.com].

== Open Source Software

This project is built on the hard work of countless open source contributors.
Several of these projects are enumerated below.

* https://asciidoctor.org/[asciidoctor]
* https://asdf-vm.com/#/[asdf]
* https://github.com/jonathanmorley/asdf-bundler[asdf-bundler]
* https://github.com/asdf-community/asdf-direnv[asdf-direnv]
* https://github.com/asdf-vm/asdf-ruby[asdf-ruby]
* https://bundler.io/[Bundler]
* https://direnv.net/[direnv]
* https://git-scm.com/[Git]
* https://jekyllrb.com/[Jekyll]
* https://github.com/asciidoctor/jekyll-asciidoc[jekyll-asciidoc]
* https://mmistakes.github.io/minimal-mistakes/[Minimal Mistakes]
* https://rouge.jneen.net/[Rouge]
* https://www.ruby-lang.org/en/[Ruby]

== Code of Conduct

The project's Code of Conduct is available in the link:CODE_OF_CONDUCT.adoc[] file.

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3], available in the link:LICENSE.adoc[] file.

The website's content is licensed under a http://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution-ShareAlike 4.0 International License].

© 2020 Jordan Williams

== Authors

mailto:{email}[{author}]
