+++
title = "About"
date = "2020-07-07"
draft = false
+++

= About
Jordan Williams
v1.0, 2020-07-07
:source-highlighter: rouge
:rouge-style: github
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Welcome to jwillikers.com, where I like to put all of my handy admin and dev guides from my myriad of tinkering.
My posts serve as convenient references for myself, but my hope is that they will help you as well.

== Me

This is my personal developer blog, so I'm taking the opportunity to talk a bit about myself.

=== On-the-job

==== Current

At my current day job, I wrangle https://isocpp.org/[{cpp}] and https://cmake.org/[CMake] code to create functional, cross-platform graphical applications.
Developing at a small company, my hands are in just about everything from project management to cross-platform application development to systems administration to licensing compliance.

.Tasks
* Aggressively updated the CMake build-system to automate as much of the brunt of dependency-management, building, testing, and packaging as possible.
* Implemented common software engineering practices:
** Version control
** Unit testing
** Micro-benchmarking
** Approval testing
** Versioning
** Contracts/Preconditions
** Changelogs
** Code reviews
* Expanded the {cpp} tooling to improve code safety:
** Enabled as many compiler warnings as possible
** Standardized formatting with https://clang.llvm.org/docs/ClangFormat.html[clang-format]
** Statically analyzed code with https://clang.llvm.org/extra/clang-tidy/[clang-tidy]
** Dynamic analyzed code with https://github.com/google/sanitizers[Google's sanitizers]
** Introduced other compilers: https://clang.llvm.org/[LLVM's Clang Compiler] and https://visualstudio.microsoft.com/vs/features/cplusplus/[Microsoft's Visual {cpp} Compiler].
* Improved build performance by using new tools:
** https://ninja-build.org/[Ninja]
** https://ccache.dev/[ccache]
* Learned from various resources how to improve code-quality and flexibility including the https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines[Cpp Core Guidelines], https://crascit.com/professional-cmake/[Professional CMake], and https://www.manning.com/books/c-plus-plus-concurrency-in-action[Concurrency in Action] to name a couple.
* Planned according to the Scrum methodology to reduce developer stress, facilitate collaboration, and keep me focused on the relevant tasks.
* Applied new {cpp} paradigms to simplify the existing codebase, such as: 
** Concepts
** Ranges
** https://fmt.dev/latest/index.html[{fmt}],
** https://en.cppreference.com/w/cpp/string/basic_string_view[string_view]
** https://en.cppreference.com/w/cpp/language/constexpr[constexpr]
** https://en.cppreference.com/w/cpp/language/lambda[lambdas]
** https://en.cppreference.com/w/cpp/thread/future[futures]
* Improved dependency management by using CMake's https://cmake.org/cmake/help/latest/module/FetchContent.html[FetchContent] functionality to directly include the source code of dependencies, building and testing them as part of the project itself.
* Fixed and verified licensing compliance with external projects.
* Packaged applications for Linux as distribution-agnostic https://appimage.org/[AppImages] with https://github.com/linuxdeploy/linuxdeploy[LinuxDeploy].
* Migrated from `{cpp}03` to `{cpp}17/20`.
* Replaced internal projects with better supported and higher-quality open-source alternatives to reduce the maintenance load of the codebase.
* Programmed cross-platform GUI applications with the https://www.qt.io/[Qt] and https://www.gtkmm.org/en/[Gtkmm], command-line tools, and libraries for Linux, macOS, and Windows.
* Enhanced error-checking and the quality of error messages.
* Converted builds to be able to build shared libraries instead of only statical libraries.
* Studied open-source projects to better understand common-practices and implementation details where documentation was insufficient or incorrect.
* Instituted conformance to Linux, macOS, and Windows standards.
* Learned how to use powerful, open-source {cpp} libraries, including:
** Boost Process
** Boost Spirit X3
** Boost Interprocess
** Boost.ut
** fmt
** Google Benchmark
** Qt
** Gtk

==== Past

Previously, I interned at a cyber security company which developed log-analyzing security software.
This was my first real introduction to software engineering, where I had the privilege to be a part of the backend developer team.
This is where I learned first-hand how the fundamental software engineering practices such as version control, testing, code-reviews, continuous integration, and deployment all fit together.
My work their included Java, Python, and Awk development as well as work on the Gradle build-system and integrating deployment to Docker.
I even underwent certification as a https://www.scrum.org/[Scrum] master.

Before that, I interned as a data analyst at a healthcare institution.
This lead to lots of SQL development and digging through backend databases.
I became proficient at writing complex SQL queries, but most importantly, I was forced to think critically.
I constantly had to question, "Where is this data coming from?" and, "What does this _really_ mean?" at all times.

=== Education

I have degree in Computer Science with a concentration in Information Insurance.
Although I prefer the applied, a degree in the more theoretical aspects of Computer Science was quite rewarding, stretching me to understand the underpinning aspects of computing.
The experience in cyber security brought with it a cautious and proactive mindset, which influences how I think about and write code today.

=== Development Interests

I like writing code to make people's lives easier.
Unfortunately, I've learned from experience that poor code has a tendency to make the lives of everyone more difficult, especially for developers.
This has ingrained in me strong convictions for utilizing standard software engineering practices, high-quality open source software, and the best tooling available to create safe and maintainable code.

There is also nothing like having fun and learning new things while solving a challenging problem.
This is why languages which pursue safety and simplicity, such as Rust and Go are my favorites.
They tend allow me to focus on the problem at hand rather than frustrate me with issues and complexities inherent in the language.

=== Side Projects

I have a few side-projects, namely, this blog, my home-network's OpenBSD router, ZFS, and contributing where and when I can to open-source projects.
This blog is statically-generated with https://gohugo.io/[Hugo], and I write the content in https://asciidoctor.org/[Asciidoctor], my favorite markup language.
https://www.openbsd.org/[OpenBSD] is an absolute gem of an operating system.
It's simplicity, practicality, and detailed documentation are what make it my favorite one to use, though I will admit it is not my daily driver.
If you haven't figured it out yet, I'm big proponent of open-source software where high-quality solutions to common problems abound.
I enjoy collaborating with other developers to improve open-source software for everyone.

=== Hobbies

As for hobbies outside of tech, I enjoy spending time with my wife, yoga, cooking, socializing, listening to podcasts and books, hiking, and generally getting outside whenever possible.
