
+++
title = "Auto Update Antigen"
categories = ["Systems"]
tags = ["Antigen", "Linux", "oh-my-zsh", "systemd", "Ubuntu", "ZSH"]
date = "2020-09-19"
draft = true
+++

. Install https://www.zsh.org/[ZSH].footnote:[https://github.com/ohmyzsh/ohmyzsh/wiki/Installing-ZSH[oh-my-zsh Wiki: Installing ZSH]]
+
[source,shell]
----
$ sudo dnf install -y zsh
----

. Add `/usr/bin/zsh` to `/etc/shells`.footnote:[https://unix.stackexchange.com/a/111367/395084]
+
[source,shell]
----
$ command -v zsh | sudo tee -a /etc/shells
/usr/bin/zsh
----

. Set the default shell to `zsh`.
+
[source,shell]
----
$ chsh -s `which zsh`
Changing shell for jordan.
Password: 
Shell changed.
----

. Now, open up a fresh terminal session to start using `zsh`.

=== oh-my-zsh

. If you don't already have https://git-scm.com/[git] install it in order to retrieve https://ohmyz.sh/[oh-my-zsh].
+
[source,shell]
----
$ sudo dnf install -y git
----

. Install the `oh-my-zsh` `git` repository.
+
[source,shell]
----
$ git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
Cloning into '/home/jordan/.oh-my-zsh'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 24904 (delta 0), reused 5 (delta 0), pack-reused 24899
Receiving objects: 100% (24904/24904), 6.99 MiB | 7.98 MiB/s, done.
Resolving deltas: 100% (12473/12473), done.
----

. Copy over the `zshrc` template file.
+
--
CAUTION: You may want to backup your existing `.zshrc` before continuing.

[source,shell]
----
$ cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
----
--

. Load the new `.zshrc` configuration file.
+
[source,shell]
----
$ source ~/.zshrc
----

=== Antigen

footnote:[https://github.com/zsh-users/antigen/wiki/Installation]

. Download the http://antigen.sharats.me/[Antigen] repository for CentOS 7.footnote[https://software.opensuse.org/download.html?project=shells%3Azsh-users%3Aantigen&package=antigen]
+
[source,shell]
----
$ wget https://download.opensuse.org/repositories/shells:zsh-users:antigen/CentOS_7/shells:zsh-users:antigen.repo
----

. Place the repository in the `/etc/yum.repos.d/` directory.
+
[source,shell]
----
$ sudo mv shells:zsh-users:antigen.repo /etc/yum.repos.d
----

. Install Antigen.
+
[source,shell]
----
$ sudo dnf install -y antigen
----

. Create the `.antigenrc` configuration file.footnote:[]
+
.~/.antigenrc
[source]
----
# Load the oh-my-zsh's library
antigen use oh-my-zsh

antigen bundles <<EOBUNDLES
    # Bundles from the default repo (robbyrussell's oh-my-zsh)
    git

    # Fish-like auto suggestions
    zsh-users/zsh-autosuggestions

    # Extra zsh completions
    zsh-users/zsh-completions

    # Syntax highlighting bundle.
    zsh-users/zsh-syntax-highlighting
EOBUNDLES

# Load the theme
antigen theme robbyrussell

# Tell antigen that you're done
antigen apply
----

. Load the Antigen configuration file from the `.zshrc` file.
+
.~/.zshrc
[source]
----
# Load Antigen 
source /usr/share/antigen.zsh 
 
# Load Antigen configurations 
antigen init ~/.antigenrc 
----

==== System-level Update Service

CentOS 7 does not support https://wiki.archlinux.org/index.php/Systemd/User[systemd user services], which seem like a good fit for updating your Antigen plugins on a schedule.
It is still possible to create a system-level unit, though, which is what these instructions describe.

. Add a https://www.freedesktop.org/wiki/Software/systemd/[systemd] service to update the Antigen plugins.
+
--
./etc/systemd/system/update-jordan-antigen.service
[source]
----
[Unit]
Description=Update Jordan's Antigen plugins for ZSH
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
User=jordan
Group=jordan
ExecStart=/usr/bin/zsh -c '. "$0" && exec "$@"' /home/jordan/.zshrc antigen update

[Install]
WantedBy=multi-user.target
----

This `systemd` unit executes the `antigen update` command after loading the `.zshrc` for the user `jordan`.footnote:[https://stackoverflow.com/a/49765275/9835303[StackOverflow: Using a user's .bashrc in a systemd service]]
This is run as the user `jordan` and it requires the network be online.
--

. Verify the `network-online.target` exists.footnote:[https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/[Running Services After the Network is up]]
+
[source,shell]
----
$ systemctl is-enabled NetworkManager-wait-online.service
enabled
----

. Test run the new `systemd` unit.
+
[source,shell]
----
$ sudo systemctl start update-jordan-antigen.service
----

. Check the output of the command to make sure everything worked.
+
[source,shell]
----
$ sudo systemctl status update-jordan-antigen.service
â— update-jordan-antigen.service - Update Jordan\'s Antigen
   Loaded: loaded (/etc/systemd/system/update-jordan-antigen.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

Sep 16 14:12:36 centos7.local systemd[1]: Starting Update Antigen...
Sep 16 14:12:37 centos7.local zsh[315]: Updating robbyrussell/oh-my-zsh@master... Done. Took 1s.
Sep 16 14:12:38 centos7.local zsh[315]: Updating zsh-users/zsh-autosuggestions@master... Done. Took 1s.
Sep 16 14:12:38 centos7.local zsh[315]: Updating zsh-users/zsh-completions@master... Done. Took 0s.
Sep 16 14:12:39 centos7.local zsh[315]: Updating zsh-users/zsh-syntax-highlighting@master... Done. Took 1s.
Sep 16 14:12:39 centos7.local systemd[1]: Started Update Antigen.
----

. Add a `systemd` timer to update the Antigen plugins once per week.
+
./etc/systemd/system/update-jordan-antigen.timer
[source]
----
[Unit]
Description=Update Antigen weekly

[Timer]
Persistent=true
OnCalendar=weekly

[Install]
WantedBy=timers.target
----

. Activate the Antigen update timer on startup.
+
[source,shell]
----
$ sudo systemctl enable update-jordan-antigen.timer
Created symlink from /etc/systemd/system/timers.target.wants/update-jordan-antigen.timer to /etc/systemd/system/update-jordan-antigen.timer.
----

==== User-level Update Service

$ mkdir -p ~/.config/systemd/user

. Add a https://www.freedesktop.org/wiki/Software/systemd/[systemd] service to update the Antigen plugins.footnote:[https://stackoverflow.com/a/49765275/9835303[StackOverflow: Using a user's .bashrc in a systemd service]]
+
.~/.config/systemd/user/update-antigen.service
[source]
----
[Unit]
Description=Update Antigen

[Service]
Type=oneshot
ExecStart=/usr/bin/zsh -c '. "$0" && exec "$@"' /home/jordan/.zshrc antigen update

[Install]
WantedBy=default.target
----

. Add a `systemd` timer to update the Antigen plugins once per week.
+
.~/.config/systemd/user/update-antigen.timer
[source]
----
[Unit]
Description=Update Antigen weekly

[Timer]
Persistent=true
OnCalendar=weekly

[Install]
WantedBy=timers.target
----

. Start the Antigen update timer upon login.footnote:[https://wiki.archlinux.org/index.php/Systemd/User#Basic_setup[Arch Wiki: systemd/user - Basic Setup]]
+
[source,shell]
----
$ systemctl --user enable update-antigen.timer
----