+++
title = "Configure Fish"
categories = ["Command-line"]
tags = ["Debian", "fish", "Linux", "Ubuntu"]
date = "2020-09-26"
draft = true
+++

I've been using https://www.zsh.org/[ZSH] for years now as my shell.
In that time, I've learned a few niceties to make the experience better.
Namely, I've found the minimal https://ohmyz.sh/[oh-my-zsh] prompt keeps out of the way and the git aliases super convenient.
Plugins for https://github.com/zsh-users/zsh-autosuggestions[autosuggestions], like in the https://fishshell.com/[fish shell], and https://github.com/zsh-users/zsh-syntax-highlighting[syntax highlighting] are also quite helpful.
http://antigen.sharats.me/[Antigen] makes keeping plugins up-to-date a breeze.

== Tutorial

This tutorial explains how to install ZSH and set it as your default shell on Ubuntu 20.04.
Plus, it details how to install and configure Antigen, oh-my-zsh, autosuggestions, and syntax highlighting.

. Install the https://launchpad.net/~fish-shell/+archive/ubuntu/release-3/+packages[fish package].
+
[source,sh]
----
$ sudo apt install -y fish
----

. Add `/usr/bin/fish` to `/etc/shells` so that is can be used as the default shell.footnote:[https://fishshell.com/docs/current/tutorial.html#switching-to-fish[fish Tutorial: Switching to fish?]]
+
[source,sh]
----
$ command -v fish | sudo tee -a /etc/shells
/usr/bin/fish
----

. Set the default shell to fish.
+
[source,sh]
----
$ chsh -s `which fish`
Changing shell for jordan.
Password: 
Shell changed.
----

. Now, open up a fresh terminal session to start using the fish shell.
+
--
You should see a fresh, vanilla shell prompt like the following.

[source,sh]
----
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
jordan@jwillkers ~>
----
--

. Configure your new shell from the convenient web interface.
+
[source,sh]
----
$ fish_config
----

. If you like that https://ohmyz.sh/[oh-my-zsh] feel like I do, you might want to use https://github.com/ohmyzsh/ohmyzsh/wiki/Themes#robbyrussell[robbyrussell's theme].
+
--
If you like doing things the old fashion way, you can make sure the appropriate directory exists and then copy over the prompt configuration straight from the command-line.

[source,sh]
----
$ mkdir -p ~/.config/fish/functions
$ cp /usr/share/fish/tools/web_config/sample_prompts/robbyrussell.fish ~/.config/fish/functions/fish_prompt.fish
----
--

. The https://ethanschoonover.com/solarized/[Solarized] color scheme is my favorite.
+
--
Setting the color theme to solarized dark can be accomplished directly from the command-line if need be.

[source,sh]
----
$ set -U fish_color_normal normal \
  set -U fish_color_command 93a1a1 \
  set -U fish_color_quote 657b83 \
  set -U fish_color_redirection 6c71c4 \
  set -U fish_color_error dc322f \
  set -U fish_color_end 268bd2 \
  set -U fish_color_selection white --bold --background=brblack \
  set -U fish_color_search_match bryellow --background=black \
  set -U fish_color_history_current --bold \
  set -U fish_color_operator 00a6b2 \
  set -U fish_color_param 839496 \
  set -U fish_color_cwd green \
  set -U fish_color_cwd_root red \
  set -U fish_color_valid_path --underline \
  set -U fish_color_autosuggestion 586e75 \
  set -U fish_color_user brgreen \
  set -U fish_color_escape 00a6b2 \
  set -U fish_color_cancel -r \
  set -U fish_pager_color_completion B3A06D
  set -U fish_pager_color_description B3A06D \
  set -U fish_pager_color_prefix cyan --underline \
  set -U fish_pager_color_progress brwhite --background=cyan \
  set -U fish_color_host normal \
  set -U fish_color_match --background=brblue \
  set -U fish_color_comment 586e75
----
--

. Update the PATH variable in fish.footnote:[https://fishshell.com/docs/current/tutorial.html#path[fish Tutorial: $PATH]]

$ set -U fish_user_paths /usr/local/bin $fish_user_paths


. Take advantage of https://fishshell.com/docs/current/tutorial.html#wildcards[recursive wildcards].

. Forget about `.fishrc`.footnote:[https://fishshell.com/docs/current/tutorial.html#startup-where-s-bashrc]

. Use up and down arrow keys instead of `Ctrl-R` for reverse history search.


== Conclusion

You should now be able to install and configure ZSH as your default shell in Ubuntu.
You should also be able to setup Antigen to use oh-my-zsh and a couple of convenient plugins.
If you want to automate updating your Antigen plugins with https://www.freedesktop.org/wiki/Software/systemd/[systemd], checkout the post <<automatically_update_antigen#,Automatically Update Antigen>>.
