+++
title = "NetBSD ATA Security Erase"
categories = ["Systems"]
tags = ["BSD", "NetBSD", "NetBSD9"]
date = "2020-08-23"
draft = true
+++

Solid state drives make excellent gifts, but it creates a problem.
How to dispose of all those old disks?
Ideally, only encrypted data has been written to the drive, making erasure simply the act of throwing out the encryption keys.
Since these aren't disks I've enabled encryption on myself, I'll have to actually erase them.
The surest way to safeguard sensitive data is to bore holes in the drive with an electric drill.
I'd like to recycle the drives at my local Best Buy, and my guess is they recycle better when they aren't riddled full of holes. 
A less destructive approach is to write zeros over the entire hard drive.
While this works for spinning rust, it doesn't overwrite all of the data on an SSD nor does it handle bad sectors.
An alternative that works for both mechanical and solid state disks is the ATA Security Erase command.

The ATA Security Erase command directs a disk to erase itself.
The https://web.archive.org/web/20110222015452/http://cmrr.ucsd.edu/people/Hughes/HDDEraseReadMe.txt[HDDErase README] succinctly describes it.
[quote, HDDEraseReadMe.txt]
____
Secure erase overwrites all user data areas with binary zeroes.  Enhanced 
secure erase writes predetermined data patterns (set by the manufacturer) to 
all user data areas, including sectors that are no longer in use due to 
reallocation.
____
Unfortunately, this relies on proprietary and properly-functioning technology within the drive, which leaves you at the mercy of the manufacturer.
This seemed an appropriate solution for my use case.
It's also worth mentioning that the ATA Security Erase command can also be used to optimize solid state disks.footnote:[https://wiki.archlinux.org/index.php/Solid_state_drive/Memory_cell_clearing[Arch Linux Wiki: Solid state drive/Memory cell clearing]]

== Tutorial

Sending Security Erase ATA commands is a fairly low-end operation in the Unix-like world.
Some operating systems support this functionality better than others.
https://www.netbsd.org/[NetBSD] has the most user-friendly interface for this functionality I was able to find built-in to an open-source operating system.
Coupling that with NetBSD's vast hardware support makes it a great option for using ATA Security Erase.
This tutorial details the steps required to issue an ATA Security Erase command to a hard drive from NetBSD 9.0.

=== Preparation

=== Steps

. Plug the laptop in.

. First, ensure the system is up-to-date.
+
[source,shell]
----
$ sudo pacman -Syuu
:: Synchronizing package databases...
  core is up to date
  extra is up to date
  community is up to date
:: Starting full system upgrade...
 there is nothing to do
----

. Next, determine which device is the onboard eMMC module.
+
--
[source,shell]
----
$ lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0          7:0    0  85.5M  1 loop /var/lib/snapd/snap/core/9806
loop1          7:1    0  85.8M  1 loop /var/lib/snapd/snap/core/9670
loop2          7:2    0 174.6M  1 loop /var/lib/snapd/snap/multipass/2446
loop3          7:3    0  62.2M  1 loop /var/lib/snapd/snap/snapcraft/5312
loop4          7:4    0  48.4M  1 loop /var/lib/snapd/snap/core18/1883
loop5          7:5    0  36.9M  1 loop /var/lib/snapd/snap/review-tools/1723
loop6          7:6    0  62.2M  1 loop /var/lib/snapd/snap/snapcraft/5282
loop7          7:7    0  48.8M  1 loop /var/lib/snapd/snap/core18/1888
loop8          7:8    0 173.6M  1 loop /var/lib/snapd/snap/multipass/2379
mmcblk2      179:0    0  58.2G  0 disk # <1>
├─mmcblk2p1  179:1    0 213.6M  0 part /boot
└─mmcblk2p2  179:2    0    58G  0 part /
mmcblk2boot0 179:32   0     4M  1 disk 
mmcblk2boot1 179:64   0     4M  1 disk 
mmcblk1      179:96   0 238.5G  0 disk # <2>
zram0        252:0    0   5.6G  0 disk [SWAP]
----
<1> In this case, `mmcblk2` is the internal 64 GB eMMC module.
<2> `mmcblk1` happens to be a connected 250 GB SD card.
--

[CAUTION]
====
Flashing to the wrong device could destroy your data.
If you have an SD card connected, you might want to unplug it to be safe.
====

. Flash `idbloader.img` to the eMMC.
+
[source,shell]
----
$ sudo dd if=/boot/idbloader.img of=/dev/mmcblk2 seek=64 conv=notrunc,fsync
322+1 records in
322+1 records out
164958 bytes (165 kB, 161 KiB) copied, 0.00663394 s, 24.9 MB/s
----

. Flash `u-boot.itb` to the eMMC.
+
[source,shell]
----
$ sudo dd if=/boot/u-boot.itb of=/dev/mmcblk2 seek=16384 conv=notrunc,fsync
1801+1 records in
1801+1 records out
922192 bytes (922 kb, 901 KiB) copied, 0.0833926 s, 11.1 MB/s
----

=== Conclusion

That's all.
You should now have the latest U-Boot booting your system!
