+++
title = "Password-less Sudo"
categories = ["Command-line"]
tags = ["Linux", "macOS", "sudo"]
date = "2020-09-19"
draft = false
+++

Typing a password to login is repetitive enough, isn't it? 
Entering the password for https://www.sudo.ws/sudo.html[Sudo] on the command-line can be downright irritating.
If you don't need that extra bit of protection, why enter your password more than you have to?footnote:[https://security.stackexchange.com/a/45728[Security StackExchange: How secure is NOPASSWD in passwordless sudo mode?]]
You can forever skip entering your `sudo` password, and it's super easy and cross-platform.
For whatever reason, I learned and forgot about doing this sometime ago, so here's the gist.

To disable password authentication for `sudo` for a user, in this case `jordan`, just run the following command.footnote:[https://linuxize.com/post/how-to-add-user-to-sudoers-in-ubuntu/#adding-user-to-the-sudoers-file[Linuxize: How to Add User to Sudoers in Ubuntu - Adding User to the sudoers File]]

[source,shell]
----
$ echo "jordan  ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/jordan
----

This just adds the line shown in <</etc/sudoers.d/jordan>>, which allows the given user to run any command with `sudo` without having to enter a password.

./etc/sudoers.d/jordan
[source]
----
jordan  ALL=(ALL) NOPASSWD:ALL
----
