+++
title = "Syntax Highlighting on the Command-line with bat"
categories = ["Command-line"]
tags = ["bat", "Linux", "less", "Rust", "Solarized", "Ubuntu", "Unix"]
date = "2020-10-11"
draft = false
+++

https://github.com/sharkdp/bat[`bat`] is a helpful alternative to https://www.gnu.org/software/coreutils/manual/html_node/cat-invocation.html#cat-invocation[`cat`] when you want peruse files on the command-line with the improved readability that syntax highlighting has to offer.
The https://www.rust-lang.org/[Rust] program boasts a wide selection of color themes, automatically uses the system pager when needed, provides syntax highlighting for man pages, and even provides basic integration with https://git-scm.com/[`git`].
It is a wonderful tool, though it won't replace your general pager, like https://github.com/rkitover/vimpager[`vimpager`], or your `git` pager, like https://github.com/dandavison/delta[`delta`].footnote:[According to https://github.com/sharkdp/bat/issues/1053[this issue], `bat` might just be it's own pager before long.]

== Tutorial

This tutorial walks through installing and configuring `bat`, version 0.16.0 at the time of writing, on an amd64 system running https://ubuntu.com/[Ubuntu] 20.04.
It assumes you are familiar with common command-line utilities on Ubuntu and the `less` pager.

. Download the deb file for the latest version of `bat` for your particular computer's CPU architecture.
+
--
Releases can be found https://github.com/sharkdp/bat/releases/[here].
The following one-liner downloads the amd64 deb installer for the latest release.

[source,sh]
----
➜ wget -q -nv -O - https://api.github.com/repos/sharkdp/bat/releases/latest \
   | awk -F': ' '/browser_download_url/ && /_amd64\.deb/ && !/musl/ {gsub(/"/, "", $(NF)); system("wget -qi -L " $(NF))}'
----
--

. Install the `bat` deb package.
+
[source,sh]
----
➜ sudo apt install -y ./bat_*_amd64.deb
----

. Clean up the remaining deb package since it is no longer needed.
+
[source,sh]
----
➜ rm bat_*_amd64.deb
----

. Create an initial configuration file.
+
[source,sh]
----
➜ bat --generate-config-file
Success! Config file written to /home/jordan/.config/bat/config
----

. Set the default color theme.
+
--
[source]
.~/.config/bat/config
----
--theme="Solarized (dark)"
----

This sets the theme to https://ethanschoonover.com/solarized/[Solarized] Dark, my favorite color scheme.
--

. Highlight syntax with `bat` when using http://greenwoodsoftware.com/less/index.html[`less`].
+
--
[source]
.~/.pam_environment
----
LESS DEFAULT="-R"
LESSOPEN DEFAULT="| bat --color always %s"
----

NOTE: You will have to log out and back in again for changes in `~/.pam_environment` to take effect.
--

. Alias `cat` to `bat` because old habits die hard.
+
[source,sh]
----
➜ alias -s cat (which bat)
----

. Highlight syntax within `man` pages.
+
[source]
.~/.pam_environment
----
MANPAGER DEFAULT="sh -c 'col -bx | bat -l man -p'"
----

. Behold that beautiful syntax highlighting.
+
[source,sh]
----
➜ man 2 select
----

== Conclusion

Reading code from the command-line should be a little bit more pleasant now.
Enjoy!
