= Install ZFS on the Pinebook Pro
:page-layout:
:page-category: Disks
:page-tags: [ArchLinux, Linux, Manjaro, PinebookPro, ZFS]

Recently, I obtained a 64-bit ARM, budget Linux laptop, the https://www.pine64.org/pinebook-pro/[Pinebook Pro].
It's a wonderful, sleek little notebook, boasting great convenience and power-efficiency.
I enjoy using it so much, it's becoming my main machine, and I'd love love to put all of my music, audiobooks, pictures, and ebooks on it.
The only problem being my media takes up a bit more than the 64 GiB available on the machine's built-in eMMC.
With a spacious microSD card in-hand, I knew it was time to get more experience with my new filesystem of choice https://openzfs.org/wiki/Main_Page[ZFS].

== Tutorial

This tutorial describes the steps required to install ZFS on a Pinebook Pro running the tailored version of Manjaro KDE.

=== Install

The ZFS software is readily available as a https://en.wikipedia.org/wiki/Dynamic_Kernel_Module_Support[DKMS] module for the arm64 architecture.
The following instructions detail how to install the ZFS DKMS module.

. First, install DKMS on the Pinebook Pro.footnote:[https://wiki.archlinux.org/index.php/Dynamic_Kernel_Module_Support[Arch Linux Wiki: Dynamic Kernel Module Support]]
+
[source,sh]
----
$ sudo pacman -S dkms linux-pinebookpro-headers
----

. The https://github.com/Jguer/yay[yay] tool provides a nifty way to install packages from the https://wiki.archlinux.org/index.php/Arch_User_Repository[AUR].
+
[source,sh]
----
$ sudo pacman -S yay
----

. Then, install the https://aur.archlinux.org/packages/zfs-dkms-any/[zfs-dkms-any] package from the AUR.
+
[source,sh]
----
$ yay -S zfs-dkms-any
----

=== Configure

It's likely you want to have ZFS available without having to explicitly load the DKMS module, import pools, and mount datasets every time you restart your computer.
These next steps describe exactly how to avoid such nonsense.

. To load the ZFS DKMS module at boot, create the appropriate file for https://www.freedesktop.org/wiki/Software/systemd/[systemd].footnote:[https://wiki.archlinux.org/index.php/Kernel_module#Automatic_module_loading_with_systemd[Arch Linux Wiki: Kernel Module - Automatic Module Loading with systemd]]
+
./etc/modules-load.d/zfs.conf
----
# Load ZFS at boot
zfs
----

. Enable importing pools and mounting datasets at boot.footnote:[https://wiki.archlinux.org/index.php/ZFS#Automatic_Start[Arch Linux Wiki: ZFS - Automatic Start]]
+
[source,sh]
----
$ sudo systemctl enable zfs-import-cache
$ sudo systemctl enable zfs-import.target
$ sudo systemctl enable zfs-mount
$ sudo systemctl enable zfs.target
----

=== Next Steps

See <<zfs_external_storage_pinebook_pro#,External Storage on the Pinebook Pro with ZFS>> to learn how to use ZFS to store your files on a microSD card.
