= Change your Shell
:page-layout:
:page-category: Command-Line
:page-tags: [BSD, fish, Linux, macOS, shell, Ubuntu]

Sometimes, you just want to switch to a better shell for your terminal - like https://fishshell.com/[fish].

== Tutorial

Here's a quick run through of how to change your default login shell which assumes you understand the basics of the command-line on Unix-like systems.
These instructions are exemplified on an Ubuntu 20.04 system for the fish shell but this works just the same for any shell on *BSD, Linux, and macOS.

. Install the fish package.
+
--
[,sh]
----
sudo apt -y install fish
----

This Debian package installs the `fish` executable in `/usr/bin`.
--

. Register `/usr/bin/fish` as a valid login shell by adding its path to https://manpages.debian.org/unstable/manpages/shells.5.en.html[`/etc/shells`].
+
--
Debian provides a convenient https://manpages.debian.org/unstable/debianutils/add-shell.8.en.html[`add-shell`] command to accomplish this.

[,sh]
----
sudo add-shell /usr/bin/fish
----

On other systems, simply add the path manually.

[,sh]
----
echo /usr/bin/fish | sudo tee -a /etc/shells
/usr/bin/fish
----
--

. Set the default login shell of the current user to fish.footnote:[https://fishshell.com/docs/current/tutorial.html#switching-to-fish[Fish Shell Tutorial - Switching to fish?]]
+
[,sh]
----
chsh -s /usr/bin/fish
Password:
----

== Conclusion

Nice and simple, right?
It should be a piece of cake to change your login shell now.
