= Git Syntax Highlighting
:page-layout:
:page-category: Command-Line
:page-tags: [delta, git, Linux, Rust, Solarized, Ubuntu, Unix]

If you like to use https://github.com/dandavison/delta[`git`] from the command-line and enjoy syntax highlighting, you might be interested in https://github.com/dandavison/delta[`delta`], which adds this functionality and more to `git`.

== Tutorial

This tutorial walks through installing and configuring `delta`, version 0.4.4 at the time of writing, on an amd64 system running https://ubuntu.com/[Ubuntu] 20.04.
It assumes you are familiar with common command-line utilities on Ubuntu, including `git`.

. Download the deb file for the latest version of `delta` specific to your computer’s CPU architecture.
+
--
Releases can be found https://github.com/dandavison/delta/releases[here].

[source,sh]
----
➜ wget -q -nv -O - https://api.github.com/repos/dandavison/delta/releases/latest \
  | awk -F': ' '/browser_download_url/ && /_amd64\.deb/ && !/musl/ {gsub(/"/, "", $(NF)); system("wget -qi -L " $(NF))}'
----

This one-liner downloads the amd64 deb installer for the latest release.
--

. Install the `delta` deb package.
+
[source,sh]
----
➜ sudo apt -y install ./git-delta_*_amd64.deb
----

. Clean up the remaining deb package since it is no longer needed.
+
[source,sh]
----
➜ rm git-delta_*_amd64.deb
----

. Use `delta` as the pager for `git`.
+
[source,sh]
----
➜ git config --global core.pager delta
----

. Stylize diff output with `delta`.
+
[source,sh]
----
➜ git config --global interactive.diffFilter "delta --color-only"
----

. Style moved blocks of code appropriately.
+
[source,sh]
----
➜ git config --global diff.colorMoved default
----

. Customize your color scheme.
+
--
This command sets the color scheme to https://ethanschoonover.com/solarized/[Solarized] Dark.

[source,sh]
----
➜ git config --global delta.syntax-theme "Solarized (dark)"
----
--

. View diffs side-by-side so that they are easier to compare.
+
[source,sh]
----
➜ git config --global delta.side-by-side true
----

. Show line numbers for reference.
+
[source,sh]
----
➜ git config --global delta.line-numbers true
----

. Turn on extra decorations to emphasize important details, such as the file and commit information.
+
[source,sh]
----
➜ git config --global delta.decorations true
----

== Conclusion

Hopefully this improves your experience analyzing `git` output and diffs from the command-line.
