= Solarized Vim
:page-layout:
:page-category: Command-Line
:page-tags: [BSD, Editor, Linux, macOS, Solarized, Ubuntu, Unix, Vim]

I enjoy the https://github.com/altercation/solarized[Solarized] color scheme, so I figured out how to set it up in https://www.vim.org/[Vim].
The Solarized color scheme provides a https://github.com/altercation/vim-colors-solarized[plugin for Vim], which makes this pretty straightfoward.
The following instructions detail how to do this on https://ubuntu.com/[Ubuntu] 20.04, but other than the installation step, this should work on any Unix-like system so long as Vim is at least version eight.
This guide assumes you are familiar with installing packages from the command-line on Ubuntu, https://git-scm.com/[git], configuring Vim, and https://github.com/vim/vim/blob/856c1110c1cf0d6e44e387b70732/runtime/doc/repeat.txt#L525[using Vim packages].footnote:[https://vi.stackexchange.com/a/9523[Vi and Vim StackExchange: What is the Vim8 package feature and how should I use it?]]

. First, install Vim and Git if you haven't already done so.
+
[,sh]
----
sudo apt -y install git vim
----

. Create a `plugins` directory according to Vim's plugin directory scheme for autoloaded plugins, i.e. `\~/.vim/pack/\*/start`.
+
[,sh]
----
mkdir -p ~/.vim/pack/plugins/start
----

. Download the Solarized plugin's git repository in this directory.
+
[,sh]
----
git clone https://github.com/altercation/vim-colors-solarized.git \
  ~/.vim/pack/plugins/start/vim-colors-solarized
----

. Optionally, update the help index with the new plugin's documentation.footnote:[https://wiki.archlinux.org/index.php/vim#Using_the_built-in_package_manager[Arch Wiki: Vim - Using the built-in package manager]]
+
--
[,sh]
----
vim -u NONE -c "helptags vim-colors-solarized/doc" -c q
----

TIP: From within Vim, access the plugin's help documentation with `:help solarized`.
--

. Enable the Solarized Dark color scheme in your Vim configuration file.
+
[source]
.~/.vim/vimrc
----
syntax enable
set background=dark
colorscheme solarized
----
