= Podman With Btrfs and ZFS
:page-layout:
:page-category: Data Storage
:page-tags: [Btrfs, containers, CoW, filesystem, Linux, Podman, ZFS]
:Btrfs: https://btrfs.wiki.kernel.org/index.php/Main_Page[Btrfs]
:containers-storage-conf: https://github.com/containers/storage/blob/master/docs/containers-storage.conf.5.md[containers-storage.conf(5)]
:fstab: http://manpages.ubuntu.com/manpages/bionic/man5/fstab.5.html[fstab(5)]
:nested-layout: https://btrfs.wiki.kernel.org/index.php/SysadminGuide#Nested[nested layout]
:Podman: https://podman.io/[Podman]
:Podman-issue-9574: https://github.com/containers/podman/issues/9547[Podman issue #9574]
:podman-rootless-tutorial-storage-conf: https://github.com/containers/podman/blob/master/docs/tutorials/rootless_tutorial.md#storageconf[storage.conf]
:podman-system-reset: https://docs.podman.io/en/latest/markdown/podman-system-reset.1.html[podman-system-reset(1)]
:ZFS: https://openzfs.org/wiki/Main_Page[ZFS]

[NOTE]
====
I now use the default `overlay` driver on Btrfs and ZFS filesystems as I've found it to _just work_.
Unless you have specific reasons for using the underlying filesystem driver, you might want to consider sticking with the default `overlay` driver.
====

{Podman} has storage backends for both {Btrfs} and {ZFS}.
Using these backends allows Podman to take full advantage of the underlying _CoW_ filesystem.
This is a quick guide on enabling these storage drivers.

== Enable the Btrfs and ZFS Storage Drivers for Podman

Below are the necessary steps to enable the {Btrfs} and {ZFS} storage drivers.
It is assumed that you are familiar with Linux, Podman, and the command-line and that you're running on a Linux system with Podman installed.
Instructions are provided for both rootless and root configurations.

. Reset Podman's storage with {podman-system-reset} before changing the storage driver.
+
--
The storage driver may only be set before initializing Podman.
It can't be changed on-the-fly.
This requires removing all storage _before_ switching the storage driver.
This must be done separately for a user's rootless configuration and the root configuration.

[WARNING]
====
This will delete all existing containers and images.
====

rootless::
+
[,sh]
----
➜ podman system reset
----

root::
+
[,sh]
----
➜ sudo podman system reset
----
--

. Set the storage backend in {containers-storage-conf}.
The system configuration file is `/etc/containers/storage.conf`.
The driver set here applies to containers run as root.
New rootless configurations will default to it if it is supported.
Only certain drivers are supported for rootless containers.
If the system configuration is set to use a driver not supported in rootless configurations, then the driver will default to the "overlay" driver if available, otherwise it will use the "vfs" driver.
A user's rootless configuration in `~/.config/containers/storage.conf` supersedes the driver in the system configuration.footnote:[To be accurate, the user's config file is located at `$XDG_CONFIG_HOME/containers/storage.conf` when `XDG_CONFIG_HOME` is set but otherwise resides at the aforementioned location.]
While the Btrfs driver is supported in rootless configurations, the ZFS driver is not, at this moment.

rootless:: When dealing with user configuration, you'll need to create the `~/.config/containers/` directory first.
+
[,sh]
----
➜ mkdir -p ~/.config/containers
----

root::
Btrfs:::
+
--
[source,toml]
./etc/containers/storage.conf
----
[storage]

driver = "btrfs"
----

[NOTE]
====
Setting the Btrfs driver here sets it as the default for _new_ rootless configurations.
====
--

ZFS:::
+
--
[source,toml]
./etc/containers/storage.conf
----
[storage]

driver = "zfs"
----

[NOTE]
====
Setting the ZFS driver here sets it for root only.
====
--

Btrfs:::
+
[source,toml]
.~/.config/containers/storage.conf
----
[storage]

driver = "btrfs"
----

ZFS:::
+
--
[NOTE]
====
This might work, but I haven't tested the ZFS driver for rootless containers.
Mileage may vary.
====

[source,toml]
.~/.config/containers/storage.conf
----
[storage]

driver = "zfs"
----
--

From here, you can configure various driver-specific options for either Btrfs or ZFS as defined in {containers-storage-conf}.
The Btrfs driver doesn't have a `mountopt` key for controlling mount options.
This owes to the fact that Podman creates Btrfs subvolumes in a {nested-layout} leading to subvolumes inheriting the mount options of their parent subvolumes.
Since my user's home directory is its own top-level subvolume mounted in {fstab}, the mount options used for it are inherited by my rootless containers.
These options include `autodefrag`, `compress=zstd`, and `noatime`, all of which I would recommend for your running containers.
You can even go so far as to create dedicated, top-level subvolumes for your root and rootless containers to fine-tune the mount options.
To learn more about Btrfs mount options and layouts, see <<btrfs-mount-options#,Btrfs Mount Options>> and <<btrfs-layout#,Btrfs Layout>>.

To really capitalize on using Btrfs and ZFS for your containers, you'll want to take advantage of their snapshot and incremental backup capabilities.
Containers, images, and named volumes are all stored in `~/.local/share/containers/storage` for rootless runtimes and `/var/lib/containers/storage/` for root.
For Btrfs, these directories contain the subdirectory `btrfs/subvolumes` which contains individual subvolumes for each container.
I assume that the ZFS driver uses a similar procedure for creating individual datasets for each container.
Snapshots can be taken of these containers and they can be backed up incrementally.

You probably use named volumes for persisting any important data in your containers such as databases and configuration.
These named volumes are located in the `volumes` subdirectory.
You might make this directory - or any of its subdirectories for that matter - a subvolume or dataset and snapshot it and back it up.
For Btrfs users, the blog posts <<btrfs-snapshot-management-with-snapper#,Btrfs Snapshot Management With Snapper>> and <<backup-snapper-snapshots-with-snap-sync#,Backup Snapper Snapshots With snap-sync>> can be applied to create automated snapshots and backups of these directories.

== Conclusion

You have combined the ultimate powers of Podman and Btrfs or ZFS.
World domination is that much closer.
Enjoy!
