= Power Management on Linux With TLP
:page-layout:
:page-category: Admin
:page-tags: [elementary, Linux, TLP, Ubuntu]
:elementary-os: https://elementary.io/[elementary OS]
:TLP: https://linrunner.de/tlp/#[TLP]
:TLPUI: https://github.com/d4nj1/TLPUI[TLPUI]
:Ubuntu: https://opensource.org/licenses/gpl-license[Ubuntu]

{TLP} is a powerful power management utility for Linux.
It helps conserve battery life on mobile Linux devices by taking advantage of various kernel features.
It's also super easy to add to a system and requires no extra configuration after installation.
Though, it does expose quite a bit of configuration settings for those who want fine-grained control.

== Tutorial

This tutorial will get {Ubuntu} and derivatives such as {elementary-OS} setup with TLP.
The instructions use the command-line and software-management utilities built into Ubuntu, so you should be familiar with these tools.

. Install the necessary package for easily adding PPA's.
+
[,sh]
----
➜ sudo apt -y install software-properties-common
----

. Add the TLP PPA to your system to get the latest version of TLP.
+
[,sh]
----
➜ sudo apt-add-repository -uy ppa:linrunner/tlp
----

. Install TLP.
+
[,sh]
----
➜ sudo apt -y install tlp tlp-rdw
----

. TLP will start automatically at boot, but to start it now without rebooting, do so manually.
+
[,sh]
----
➜ sudo tlp start
----

== Conclusion

That's it.
Really.
If you want to tweak the settings, I recommend checking out the graphical user interface provided by {TLPUI}.
You now know how to quickly configure better power-savings on your Linux devices.
