= Backup and Restore a GPG Key
:page-layout:
:page-category: Systems
:page-tags: [Backups, GnuPG, GPG, OpenPGP, Ubuntu]

https://gnupg.org/[Gnu Privacy Guard], also known as GnuPG and GPG, is a handy tool for managing https://www.openpgp.org/[OpenPGP] keys.
While don't use PGP keys for email encryption as many people do, I do use a PGP key to sign my work when using https://git-scm.com/[Git].
PGP keys can be a bit nastier to replace than an SSH key, so making backups is critical for reducing future headaches.

== Tutorial

The following steps will show you how to backup and restore a PGP key using GnuPG, version 2.2.20 to be exact.
It is expected you are already familiar using GnuPG from the command-line and have an existing installation of GPG with a freshly generated key pair available to backup.

=== Backup

https://unix.stackexchange.com/a/482559
https://wiki.archlinux.org/index.php/GnuPG#Backup_your_private_key

You _must_ backup your private key.
You might as well backup your public key and trust while your at it, though.

. First, determine which key to backup.
+
[source,sh]
----
➜ gpg 
----

. Optionally, you can backup the trustdb to a file as well.
+
[source,sh]
----
➜ gpg --export-ownertrust > otrust.txt
----

gpg --export -o public.gpg
gpg --export-secret-keys -o private.gpg --export-options keep-ownertrust export-backup

=== Restore

gpg --import public.gpg
gpg --import-secret-keys -o private.gpg --import-options import-restore
gpg --import-ownertrust otrust.txt

. Restore the trustdb.
+
[source,sh]
----
➜ gpg --import-ownertrust < otrust.txt
----

== Conclusion
