+++
title = "Local ZFS Backups"
categories = ["Systems"]
tags = ["Backups", "Linux", "Ubuntu", "Ubuntu2004", "ZFS"]
date = "2020-07-04"
draft = true
+++

= Local ZFS Backups
Jordan Williams <jordan@jwillikers.com>
v1.0, 2020-07-04

ZFS is 

== Tutorial

This tutorial describes the steps required to backup user data to an external disk using ZFS on Ubuntu 20.04.

=== Create the Pool

First, determine which device is the external hard drive.

[source,console]
----
$ sudo fdisk -l
Disk /dev/sdb: 931.49 GiB, 1000170586112 bytes, 1953458176 sectors
Disk model: easystore 25FC  
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 00000000-0000-0000-0000-000000000001
----

In this case, `/dev/sdb` is the 1 TB external hard drive.

Next, determine the disk id to use when creating the zpool.footnote:[https://wiki.archlinux.org/index.php/ZFS#Identify_disks[Arch Linux Wiki: Identify Disks]]

[source,console]
----
$ ls -lh /dev/disk/by-id/ | grep -w sdb
lrwxrwxrwx 1 root root  9 Jul  4 07:23 usb-WD_easystore_25FC_000000000000000000000001-0:0 -> ../../sdb
----

// Is this necessary?
Then, double-check the block size.

[source,console]
----
$ sudo blockdev --getpbsz /dev/sdb
512
----

The SD card's block size is 512 MiB, which means `ashift` should be set to 12.footnote:[https://wiki.archlinux.org/index.php/ZFS#Advanced_Format_disks[Arch Linux Wiki: ZFS - Advanced Format Disks]]

Create the pool.footnote:[https://wiki.archlinux.org/index.php/ZFS#Creating_ZFS_pools[Arch Linux Wiki: ZFS - Creating ZFS Pools]]

[source,console]
----
$ sudo zpool create \
  -o ashift=12 \
  -O compression=on \ <1>
  backup_pool usb-WD_easystore_25FC_000000000000000000000001-0:0
----
<1> Turn on compression by default.

Take a snapshot.

[source,console]
----
$ sudo zfs snapshot -r rpool/USERDATA/jordan@2020-07-04-13:00:58
----

// Export the backup pool.

// [source,console]
// ----
// $ zpool export backup_pool
// ----

=== Incremental Backups

Incrementally send data between the last two backups.

[source,console]
----
$ zfs send \
  --replicate \ # <1>
  -i 2020-07-04-13:00:00 rpool/USERDATA/jordan@2020-07-04-14:00:00 \ # <2>
  | zfs receive -dvu backup_pool
----
<1> Stream the data.
<2> Send the incremental for the snapshots of `USERDATA/jordan` at 13:00 and 14:00 on July 4th.

=== Restore

You can do a complete restoration of the entire dataset, or otherwise mount it.

Retrieve the snapshot.

[source,console]
----
$ zfs send --replicate backup_pool/USERDATA/jordan@2020-07-04-14:00:00 | zfs receive -dvu rpool
----

Revert to the snapshot.

[source,console]
----
$ sudo zfs rollback -r rpool/USERDATA/jordan@2020-07-04-14:00:00
----

=== Verify

