+++
title = "PPPoE on OpenBSD"
categories = ["Networking"]
tags = ["PPPoE", "OpenBSD", "OpenBSD 6", "OpenBSD 6.6", "Networking", "Routing"]
date = "2020-02-09"
draft = false
+++

= Setup PPPoE on OpenBSD 6.6
Jordan Williams <jordan@jwillikers.com>
v1.0, 2020-03-09
:source-highlighter: rouge
:rouge-style: base16.solarized.dark
:icons: font
ifndef::env-github[]
:imagesdir: ./
endif::[]
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

This brief article describes how I setup the internet connection on my PPPoE interface on OpenBSD 6.6.

== PPPoE Configuration

The configuration only involves two configuration files and initializing the new network interface.
I use a https://man.openbsd.org/OpenBSD-6.6/hostname.if[hostname.if] file to initialize the PPPoE interface when the system boots.
This example is very similar to the one provided in the https://man.openbsd.org/OpenBSD-6.6/pppoe[PPPOE(4)] manpage with two differences.
First, `chap` replaces `pap` as the authentication protocal.
Second, only the relevant IPv4 options are shown since my ISP doesn't support IPv6.

./etc/hostname.pppoe0
[source]
----
inet 0.0.0.0 255.255.255.255 NONE \ # <1>
	pppoedev em0 authproto chap \ # <2>
	authname 'username' authkey 'password' up
dest 0.0.0.1
!/sbin/route add default -ifp pppoe0 0.0.0.1
----
<1> Set the IP to `0.0.0.0`, a wildcard representing whatever IP the PPPoE connection provides.
<2> `em0` is the ethernet interface for the router's WAN port.

The physical `em0` interface must be up.

./etc/hostname.em0
[source]
----
up mtu 1508
----

Start up the `em0` and `pppoe0` interfaces.
[source,console]
----
sh /etc/netstart em0 pppoe0
----

[CAUTION]
====
The `/etc/netstart` script was not able to successfully establish a PPPoE connection when I changed my configuration from `pap` to `chap`.
I had to reboot my system after changing the configuration file for the connection to succeed.

[source,console]
----
reboot
----
====
