+++
title = "DNSSEC with Unbound"
categories = ["Networking"]
tags = ["BSD", "DNS", "DNSSEC", "Internet", "Network", "OpenBSD", "OpenBSD 6", "OpenBSD 6.6", "Router", "Routing", "Unbound", "Unix"]
date = "2020-03-11"
draft = true
+++

= Setup PPPoE on OpenBSD 6.6
Jordan Williams <jordan@jwillikers.com>
v1.0, 2020-03-11
:source-highlighter: rouge
:rouge-style: base16.solarized.dark
:icons: font
ifndef::env-github[]
:imagesdir: ./
endif::[]
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Ever want to enable https://en.wikipedia.org/wiki/Domain_Name_System_Security_Extensions[DNSSEC] on your https://nlnetlabs.nl/projects/unbound/about/[Unbound] OpenBSD 6.6 server?
Me too!
Using this http://www.lonecpluspluscoder.com/2020/01/16/building-an-openbsd-wireguard-vpn-server-part-2-unbound-dns-setup/[article] as a guide, I document the process.

== Unbound Configuration

Use the https://man.openbsd.org/ftp.1[ftp] command to download the https://wiki.archlinux.org/index.php/unbound#Root_hints[Root Hints].

[source,console]
----
ftp -o /var/unbound/etc/root.hints https://www.internic.net/domain/named.root
----

Download the trust anchor file with the https://man.openbsd.org/unbound-anchor[unbound-anchor] utility.

[source,console]
----
unbound-anchor
----

Configure https://man.openbsd.org/unbound.conf[unbound.conf].
Add the location of the `root.hints` file and uncomment the lines with the keys `auto-trust-anchor-file` and `val-log-level`.

./var/unbound/etc/unbound.conf
[source]
----
# Uncomment to enable DNSSEC validation.
#
root-hints: "/var/unbound/etc/root.hints" # <1>
auto-trust-anchor-file: "/var/unbound/db/root.key"
val-log-level: 2
----
<1> This line was added, not uncommented... to be fair.

[NOTE]
====
Make sure the upstream resolvers support DNSSEC.
The https://dnscrypt.info/public-servers[list provided by DNSCrypt] has some good options.

[source]
----
# Use an upstream forwarder (recursive resolver) for some or all zones.
#
forward-zone:
	name: "."				# use for ALL queries
	forward-addr: 176.103.130.132 # adguard-dns-family
	forward-addr: 185.228.168.10 # cleanbrowsing-adult
----
====

Verify the configuration of unbound.conf which http://man.openbsd.org/unbound-checkconf.8[unbound-checkconf].

[source,console]
----
unbound-checkconf
----

Finally, restart Unbound.

[source,console]
----
rcctl restart unbound
----

Verify that DNSSEC is working with the https://man.openbsd.org/OpenBSD-6.6/dig[dig] command.
This website, `jwillikers.com`, has DNSSEC enabled and so makes for a good address to test.
Cloudflare provides a nice write-up https://support.cloudflare.com/hc/en-us/articles/360021111972-Troubleshooting-DNSSEC#TroubleshootingDNSSEC-DNSSECinPracticewithDig[here].

[source,console]
----
dig jwillikers.com +dnssec
----

[source]
----
;; flags: qr rd ra ad;
----
