+++
title = "DNSSEC with Unbound"
categories = ["Networking"]
tags = ["BSD", "DNS", "DNSSEC", "Internet", "Network", "OpenBSD", "OpenBSD 6", "OpenBSD 6.6", "Router", "Routing", "Unbound", "Unix"]
date = "2020-03-28"
draft = false
+++

= Setup PPPoE on OpenBSD 6.6
Jordan Williams <jordan@jwillikers.com>
v1.0, 2020-03-28
:source-highlighter: rouge
:rouge-style: github
:icons: font
ifndef::env-github[]
:imagesdir: ./
endif::[]
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Ever want to enable https://en.wikipedia.org/wiki/Domain_Name_System_Security_Extensions[DNSSEC] on your https://nlnetlabs.nl/projects/unbound/about/[Unbound] OpenBSD 6.6 server?
Me too!
Using this http://www.lonecpluspluscoder.com/2020/01/16/building-an-openbsd-wireguard-vpn-server-part-2-unbound-dns-setup/[article] as a guide, I document the process.

== Unbound Configuration

Use the https://man.openbsd.org/ftp.1[ftp] command to download the https://wiki.archlinux.org/index.php/unbound#Root_hints[Root Hints].

[source,console]
----
ftp -o /var/unbound/etc/root.hints https://www.internic.net/domain/named.root
----

Download the trust anchor file with the https://man.openbsd.org/unbound-anchor[unbound-anchor] utility.

[source,console]
----
unbound-anchor
----

Configure https://man.openbsd.org/unbound.conf[unbound.conf].
Add the location of the `root.hints` file and uncomment the lines with the keys `auto-trust-anchor-file` and `val-log-level`.

./var/unbound/etc/unbound.conf
[source]
----
# Uncomment to enable DNSSEC validation.
#
root-hints: "/var/unbound/etc/root.hints" # <1>
auto-trust-anchor-file: "/var/unbound/db/root.key"
val-log-level: 2
----
<1> This line was added, not uncommented... to be fair.

[NOTE]
====
Make sure the upstream resolvers support DNSSEC.
The https://dnscrypt.info/public-servers[list provided by DNSCrypt] has some good options.

[source]
----
# Use an upstream forwarder (recursive resolver) for some or all zones.
#
forward-zone:
	name: "." # use for ALL queries
	forward-addr: 176.103.130.132 # adguard-dns-family
	forward-addr: 185.228.168.10 # cleanbrowsing-adult
----
====

Verify the configuration of unbound.conf which http://man.openbsd.org/unbound-checkconf.8[unbound-checkconf].

[source,console]
----
unbound-checkconf
----

Finally, restart Unbound.

[source,console]
----
rcctl restart unbound
----

Verify that DNSSEC is working with the https://man.openbsd.org/OpenBSD-6.6/dig[dig] command from a computer using your unbound server.
This website, `jwillikers.com`, has DNSSEC enabled and so makes for a good address to test.
Cloudflare provides a nice write-up about using dig to verify DNSSEC https://support.cloudflare.com/hc/en-us/articles/360021111972-Troubleshooting-DNSSEC#TroubleshootingDNSSEC-DNSSECinPracticewithDig[here].

[source,console]
----
dig jwillikers.com +dnssec
----

The example below contains the appropriate response with DNSSEC enabled.
Look for the `ad` flag and the `RRSIG` entry.

[source]
----

; <<>> DiG 9.11.5-P4-5.1ubuntu2.1-Ubuntu <<>> jwillikers.com +dnssec
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46922
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1 # <1>

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;jwillikers.com.			IN	A

;; ANSWER SECTION:
jwillikers.com.		300	IN	A	104.28.26.241
jwillikers.com.		300	IN	A	104.28.27.241
jwillikers.com.		300	IN	RRSIG	A 13 2 300 20200329192309 20200327172309 34505 jwillikers.com. DcQzhWhlVflaeqCkZn92X6jRMJvtFySr7wN1AzGaJVk7/b4JbS/lqqZB ZepEA6FP3bHz8g5H6zduVKKv/D8Tqg== # <2>

;; Query time: 35 msec
;; SERVER: 192.168.6.1#53(192.168.6.1)
;; WHEN: Sat Mar 28 13:23:09 CDT 2020
;; MSG SIZE  rcvd: 185
----
<1> The `ad` flag is present in the list of flags.
<2> The `RRSIG` entry.
