+++
title = "UniFi Controller"
categories = ["Networking"]
tags = ["Containers", "Docker", "Docker Compose", "Ubuntu", "Ubuntu 20.04", "UniFi", "UniFi Controller"]
date = "2020-05-30"
draft = false
+++

= UniFi Controller
Jordan Williams <jordan@jwillikers.com>
v1.0, 2020-05-30
:source-highlighter: rouge
:rouge-style: github
:icons: font
ifndef::env-github[]
:imagesdir: ./
endif::[]
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

For wi-fi, I use use a https://www.ui.com/unifi/unifi-ap/[UniFi AP].
One slightly annoying aspect of this the https://www.ui.com/download/unifi/unifi-ap[UniFi Controller]. If you don't have a smartphone or need to manage more than one device, you'll need to set one up.
I provide a brief tutorial for setting up the UniFi Controller with https://docs.docker.com/compose/[Docker Compose] here.

== Tutorial

An existing https://hub.docker.com/r/linuxserver/unifi-controller[Docker image] makes setting up the UniFi Controller a breeze.
Here's how.

=== Install Docker

Install Docker Compose.

[source,console]
----
$ apt install docker-compose
----

Add your user to the `docker` group if you want to run docker without requiring superuser privileges.

[source,console]
----
$ usermod -aG docker $USER
----

Reboot to complete the installation.

[source,console]
----
$ reboot
----

=== Compose

With Docker installed, create a directory for the `docker-compose` file.

[source,console]
----
$ mkdir unifi_controller
$ cd unifi_controller
----

The provided `docker-compose` file requires just one tweak.
The volume must be configured.

.docker-compose
----
---
version: "2.1"
services:
  unifi-controller:
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M #optional
    volumes:
      - data-volume:/var/unifi-controller/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    restart: unless-stopped

volumes:
  data-volume:
----

The `docker-compose` should be pretty self-explanatory.
It really just forwards the necessary ports from the Docker container to the host machine.

Once configured, run the container.

[source,console]
----
$ docker-compose up -d
----

Then, just open the UniFi Controller's web UI.

[source,console]
----
$ xdg-open http://127.0.0.1:8443
----
