name: Build Jekyll site

"on":
  pull_request:
    branches: [main]
    paths:
      - "**.nix"
      - .github/workflows/build.yaml
      - flake.lock
      - Gemfile
      - Gemfile.lock
      - .bundle/config
      - .ruby-version
      - _data/
      - _drafts/
      - _includes/
      - _pages/
      - _posts/
      - _config.yml
      - index.adoc
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      # todo Cache bundler stuff?
      - name: Build with Jekyll
        run: nix build
