name: Check files with treefmt
"on":
  pull_request:
    branches: ["main"]
    paths:
      - "**.css"
      - "**.html"
      - "**.json"
      - "**.just"
      - "**.nix"
      - "**.scss"
      - "**.toml"
      - "**.yaml"
      - "**.yml"
      - "**/.justfile"
      - "**/justfile"
      - .github/workflows/treefmt.yaml
      - flake.lock
  push:
    branches: ["main"]
    paths:
      - "**.css"
      - "**.html"
      - "**.json"
      - "**.just"
      - "**.nix"
      - "**.scss"
      - "**.toml"
      - "**.yaml"
      - "**.yml"
      - "**/.justfile"
      - "**/justfile"
      - .github/workflows/treefmt.yaml
      - flake.lock

jobs:
  treefmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@v19
      - name: Run treefmt
        run: nix develop --command treefmt --fail-on-change --no-cache
      - uses: reviewdog/action-suggester@v1
        with:
          fail_on_error: true
          github_token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          tool_name: treefmt
