name: yamllint
"on":
  pull_request:
    branches: ["main"]
    paths:
      - "**.nix"
      - "**.yaml"
      - "**.yml"
      - .github/workflows/yamllint.yaml
      - .yamllint.yaml
      - flake.lock
  push:
    branches: ["main"]
    paths:
      - "**.nix"
      - "**.yaml"
      - "**.yml"
      - .github/workflows/yamllint.yaml
      - .yamllint.yaml
      - flake.lock

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - name: Check YAML files
        run: nix develop --command yamllint --format github .
